[package]
name = "minesweeper-rs"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
winrt = { git = "https://github.com/microsoft/winrt-rs" }
rand = "0.7.3"
bindings = { path = "bindings" }

[target.'cfg(target_vendor = "pc")'.dependencies]
winit = "0.22.2"
raw-window-handle = "0.3.3"

[target.'cfg(target_vendor = "uwp")'.dependencies]
com = "0.2.0"

[features]
show-mines = []
