[package]
name = "minesweeper-rs"
version = "0.1.0"
authors = ["Robert Mikhayelyan <rob.mikh@outlook.com>"]
edition = "2018"

[dependencies]
winit = "0.22.0"
raw-window-handle = "0.3.3"
winrt = "0.7.0"
rand = "0.7.3"

[build-dependencies]
winrt = "0.7.0"

[features]
show-mines = []